name: CI/CD security
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
#JOB 1
  security-scan:
    name: Security & Tests
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      # Criar .env dummy porque não temos no repositório
      - name: Create dummy .env file
        run: |
          echo "JWT_SECRET=segredo_super_secreto_para_testes" >> .env
          echo "PORT=7100" >> .env
          
      # Run unit tests
      - name: Build e testes (JUnit)
        run: mvn clean test

      # CodeQL - SAST
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java
          
      - name: Build for CodeQL Analysis
        run: mvn clean compile
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      # Trivy
      - name: Complete scan with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'                      
          scanners: 'vuln,secret,config'     
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

      - name: Upload artifact to pipeline metadata
        uses: actions/upload-artifact@v4
        with:
          name: Generate artifact with Trivy result
          path: trivy-results.sarif

  build-and-push:
    name: Build & Push Docker
    needs: security-scan # Dependencia
    runs-on: ubuntu-latest
    permissions:
      packages: write       # Permissão para escrever no GHCR
      contents: read
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Setup QEMU para emulação multi-arch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Push multi-arch (AMD64 + ARM64)
      - name: Push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
